import type { Metadata } from "next";
import { Inter,Calistoga,Poppins  } from "next/font/google";
import {twMerge} from "tailwind-merge"
import "./globals.css";



const inter= Inter({subsets:['latin'],variable:"--font-sans",weight:['400']})

const calistoga=Calistoga({subsets:["latin"],variable:"--font-serif",
  weight:["400"]
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ['400', '700'], // Adjust weights as needed
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(inter.variable,calistoga.variable,poppins.variable,"bg-gray-900 text-white font-sans antialiased")}>{children}</body>
    </html>
  );
}
